config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # resources :rows, only: [:index, :show]

  resources :gardens, only: [:index, :show, :new, :create, :destroy] do
    resources :rows, only: [:new, :create, :show, :index] do
      resources :garden_vegetables, only: [:new, :create, :show, :index]
    end
  end
  resources :rows, only: [:destroy]
  resources :garden_vegetables, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/garden.rb
class Garden < ApplicationRecord
  belongs_to :user
  has_many :rows, dependent: :destroy
  has_many :garden_vegetables, through: :rows
  validates :title, presence: true, uniqueness: true
end

app/models/garden_vegetable.rb
class GardenVegetable < ApplicationRecord
  belongs_to :row
  belongs_to :vegetable
  has_many :seeds, dependent: :destroy
  has_many :plants, dependent: :destroy
  has_many :harvests, dependent: :destroy

  validates :vegetable, presence: true
end

app/models/harvest.rb
class Harvest < ApplicationRecord
  belongs_to :garden_vegetable
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden_vegetable
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :vegetable1, class_name: "Vegetable"
  belongs_to :vegetable2, class_name: "Vegetable"
end

app/models/row.rb
class Row < ApplicationRecord
  belongs_to :garden
  has_many :garden_vegetables, dependent: :destroy
  has_many :vegetables,        through: :garden_vegetables
  has_many :seeds,             through: :garden_vegetables
  has_many :plants,            through: :garden_vegetables
  has_many :harvest,           through: :garden_vegetables
  validates :length, presence: true
  validates :width, presence: true

end

app/models/seed.rb
class Seed < ApplicationRecord
  belongs_to :garden_vegetable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :garden
end

app/models/vegetable.rb
class Vegetable < ApplicationRecord
  has_many :garden_vegetables
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/garden_vegetables_controller.rb
class GardenVegetablesController < ApplicationController

  def index
    @garden_vegetables = GardenVegetable.all
  end

  def new
    @garden_vegetable = GardenVegetable.new
  end

  def create
    @garden_vegetable = GardenVegetable.new(garden_vegetable_params)
    @row = Row.find(params[:row_id])
    @garden_vegetable.row = @row

    if @garden_vegetable.save
      redirect_to garden_path(@row.garden)
    else
      render "gardens/show"
    end
  end

  private

  def garden_vegetable_params
    params.require(:garden_vegetable).permit(:vegetable_id, :row_id)
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :load_garden, only: [:show, :destroy, :edit]

  def index
    @gardens = Garden.all
  end

  def show
    @row = Row.new
    @rows = Row.all
    @vegetables = Vegetable.all
  end

  def new
    @garden = Garden.new
  end

  def create

    @garden = Garden.new(garden_params)
    @garden.user_id = current_user.id
    @row = Row.create(width: 4, length: 4, garden: @garden)
    if @garden.save
      redirect_to garden_path(@garden)
    else
      render :new
    end
  end

  def destroy
    @garden.destroy
    redirect_to gardens_path
  end

  def edit

  end

  private

  def load_garden
    @garden = Garden.find(params[:id])
  end

  def garden_params
    params.require(:garden).permit(:title)
  end
end

app/controllers/harvests_controller.rb
class HarvestsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def show
    @rows = Row.all
    @garden_vegetables = GardenVegetable.all
    @vegetables = Vegetable.all
    @plants = Plant.all
  end
end

app/controllers/rows_controller.rb
class RowsController < ApplicationController
  before_action :set_row, only: [:destroy, :index]

  def index
    @rows = Row.all
  end

  def show
    @garden_vegetables = GardenVegetable.all
  end

  def new
    @row = Row.new
  end

  def create
    @garden = Garden.find(params[:garden_id])
    @row = Row.new(row_params)
    @row.garden = @garden

    if @row.save
      redirect_to garden_path(@garden)
    else
      render "gardens/show"
    end
  end

  def destroy
    @row.destroy
    redirect_to garden_path(@row.garden)
  end

  private

  def row_params
    params.require(:row).permit(:width, :length, :garden_id)
  end

  def set_row
    @row = Row.find(params[:id])
  end
end

app/controllers/seeds_controller.rb
class SeedsController < ApplicationController

  # def create
  # @seed = Seed.new(seed_params)
  # if @seed.save
  #   redirect_to garden_path(@seed.garden_vegetable.garden)
  # else
  #   render :new
  # end

  # private
  # def seed_params
  #   params.require(:seed).permit(:vegetable)
  # end
end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController
  def index
    @vegetables = Vegetable.all
  end

  def show
    @vegetable = Vegetable.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/garden_vegetables/new.html.erb
<h1>Ajouter un légume</h1>
<div>
  <%= simple_form_for [@garden, @row, @garden_vegetable] do |f| %>
    <%= f.association :vegetable %>

    <%= f.submit 'Ajouter un Légume', class: 'btn btn-success' %>
  <% end %>
</div>

app/views/gardens/_form.html.erb
  <div>
  <%= simple_form_for garden do |f| %>
    <%= f.input :title %>
    <%= f.submit 'Create garden', class: 'btn btn-success' %>
  <% end %>

</div>

app/views/gardens/index.html.erb
<div class="d-flex flex-column p-3 ">
 <% @gardens.each do |garden| %>
  <div class="m-2 p-3 border">
    <%= link_to "Go to", garden_path(garden), class: 'font-weight-bolder text-dark' %>
    <%= garden.title %>

    <%= link_to 'delete garden', garden_path(garden), class: 'btn btn-outline-danger btn-sm', method: 'delete', data: { confirm: 'Are you sure? Really?' } %>

  </div>
 <% end %>
  <p><%= link_to 'New Garden', new_garden_path, class: 'btn btn-primary' %></p>

</div>

app/views/gardens/new.html.erb
<h1>Create your garden</h1>

<%= render 'form', garden: @garden %>

app/views/gardens/show.html.erb
<h1><%= @garden.title.upcase %></h1>

  <%= render 'rows/show' %>
  <%= render 'vegetables/index' %>
  <%#= render 'garden_vegetables/new' %>


<div class="add-row border m-3">
  <%= render 'rows/new' %>
</div>

  <p><%= link_to 'Back Home', gardens_path, class: 'btn btn-primary' %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BonnesHerbes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/plants/plants.html.erb
<%= plants.count %>

app/views/rows/_new.html.erb
  <div class= "p-3">
    <h4>Ajouter une planche de culture</h4>
    <%= simple_form_for ([@garden, @row])  do |f| %>
      <%= f.input :length, as: :numeric %>
      <%= f.input :width, as: :numeric %>
      <%= f.submit 'Créer ma planche', class: 'btn btn-success' %>
    <% end %>

</div>

app/views/rows/_show.html.erb
<div class="d-flex flex-column p-3 ">
  <% @garden.rows.each do |row| %>
    <div class=" row d-flex flex-column m-2 p-3 border ">
    <h5><%= row.id %></h5>
    <% row.garden_vegetables.each do |garden_vegetable| %>
        <div class="">
        <%=  garden_vegetable.vegetable.specie %>
          <%  garden_vegetable.seeds.each do |seed| %>
            <%= seed.comment %>
            <%= seed.date %>
            <%= seed.quantity %>
            <%= seed.done %>
          <% end %>
          <%=  garden_vegetable.plants.each do |plant| %>
            <%= plant.comment %>
            <%= plant.date %>
            <%= plant.quantity %>
            <%= plant.done %> %>
          <% end %>

          <%=  garden_vegetable.harvests.each do |harvest| %>
            <%= harvest.comment %>
            <%= harvest.date %>
            <%= harvest.quantity %>
            <%= harvest.done %> %>
          <% end %>

        </div>
    <% end %>
          <%= link_to 'Supprimer la planche', row_path(row), class: 'btn btn-outline-danger btn-sm', method: 'delete', data: { confirm: 'Etes vous sur ? Vraiment ?' } %>
          <p><%= link_to 'Ajouter un légume', new_garden_row_garden_vegetable_path(@garden.id, row), class: 'btn btn-primary' %></p>

    </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/vegetables/_index.html.erb
<div class="border d-flex flex-direction-column">
  <% @vegetables.each do |vegetable| %>
    <h5 class="p-2">  <%= vegetable.specie %></h5>
    <p class="p-2"> A semer du <%= vegetable.seed_start.strftime("%m %b") %> au <%= vegetable.seed_end.strftime("%m %b") %></p>
  <% end %>
</div>